### ISSUE TITLE
List of completed tasks within next few days

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Internship#79]
Deadline ping - 

- @anuragsarkar - I think 90+ blog posts should have been live till now, let's finish in next few days, any questions ping me. Current stats are 90,849 hits, target a million useful view till end of this month. @sakshivij will join in you writing blogs posts after gif completion.
- @Armorer96 - Timed API output should have been present, let's finish in next few days, any questions ping me.
- @prondubuisi - 8/9 topics data we should have had, as discussed yesterday, I will add a sample, submit the work as I suggested
- @sakshivij - 50+ gifs should have been out, see if you can automate the gif creation
- @sujaykumarreddy - as discussed till profile creation the app should have worked, let's finish, any questions ping me.

- @tapaswenipathak - Get the patches from kernel mailing list + timer API
- @tapaswenipathak - Implements API intergrations in CFP app
- @tapaswenipathak - Adds a sample on how the data collection should be
- @tapaswenipathak - Creates GENOME visualisations
- @tapaswenipathak - any help you need in tasks, feel free in letting me know after spending time

**Comment by sakshivij** [comment]
👍
